[GLOBAL]
pants_version = "2.8.0"
backend_packages = [
    "pants.backend.shell",
    "pants.backend.codegen.protobuf.python",
    "pants.backend.python",
    #"pants.backend.python.lint.bandit",
    "pants.backend.python.lint.black",
    #"pants.backend.python.lint.docformatter",
    #"pants.backend.python.lint.flake8",
    #"pants.backend.python.lint.isort",
    #"pants.backend.python.lint.pylint",
    #"pants.backend.python.lint.yapf",
    #"pants.backend.experimental.python.lint.autoflake",
]
build_patterns = ["PANTSBUILD", "PANTSBUILD.*"]

[tailor]
build_file_name = "PANTSBUILD"

[anonymous-telemetry]
enabled = false

[source]
#root_patterns = [
#    '/lte/gateway/python',
#    '/orc8r/gateway/python',
#]
marker_filenames = ["setup.py"]

[python-protobuf]
# Use the path to the `python_requirement` targets,
# e.g. `3rdparty/python:protobuf`.
runtime_dependencies = ["//lte/gateway/python:grpcio", "//lte/gateway/python:protobuf"]
