name: Backport
on:
  pull_request_target:
    types:
      - closed
      - labeled

jobs:
  backport:
    name: Backport
    runs-on: ubuntu-latest
    # Only react to merged PRs for security reasons.
    # See https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target.
    if: >
      github.event.pull_request.merged
      && (
        github.event.action == 'closed'
        || (
          github.event.action == 'labeled'
          && contains(github.event.label.name, 'apply-')
        )
      )
    steps:
      - name: Backport Action
        uses: sqren/backport-github-action@v8.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          auto_backport_label_prefix: apply-

      - name: Info log
        if: ${{ success() }}
        run: cat /home/runner/.backport/backport.info.log

      - name: Debug log
        if: ${{ failure() }}
        run: cat /home/runner/.backport/backport.debug.log
