# Copyright 2022 The Magma Authors.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: "Build VM Development"

on:
  pull_request:
    types: [ opened, reopened, synchronize ]
  push: null

jobs:
  packer:
    runs-on: ubuntu-latest
    steps:

      - name: Install Virtualbox
        run: |
          wget -q -O- https://www.virtualbox.org/download/oracle_vbox_2016.asc | sudo gpg --dearmor --yes --output /usr/share/keyrings/oracle-virtualbox-2016.gpg
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/oracle-virtualbox-2016.gpg] https://download.virtualbox.org/virtualbox/debian $(lsb_release -cs) contrib" | sudo tee /etc/apt/sources.list.d/virtualbox.list
          sudo apt update && sudo apt install virtualbox virtualbox-dkms linux-headers-generic
          sudo dpkg-reconfigure virtualbox-dkms

      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # pin@v3

      - run: packer init .
        working-directory: orc8r/tools/packer

      - name: Fix Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: fix
          target: test.json
          working_directory: orc8r/tools/packer

      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: test.json
          working_directory: orc8r/tools/packer

      - name: Build Artifact
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-on-error=abort"
          target: test.json
          working_directory: orc8r/tools/packer
        env:
          PACKER_LOG: 1
